# Refer to: https://docs.influxdata.com/influxdb/v2/install/use-docker-compose/
services:
  db:
    image: postgres:17.2
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookmark
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./docker/postgres/stored.sql:/docker-entrypoint-initdb.d/stored.sql
      - ./docker/postgres/tdata.sql:/docker-entrypoint-initdb.d/tdata.sql

  mongo:
    image: mongo:8.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  influxdb2:
    image: influxdb:2.7.11
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my_super_secret_token
      DOCKER_INFLUXDB_INIT_ORG: bookmark
      DOCKER_INFLUXDB_INIT_BUCKET: home
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  # https://www.jaegertracing.io/docs/1.63/getting-started/
  # run by `docker compose --profile monitoring up -d`
  jaeger:
    image: jaegertracing/all-in-one:1.63.0
    # profiles:
    #   - tracing
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # ダッシュボード用のポート
      - "4318:4318" # exporterの利用するプロトコル: HTTP
      - "4317:4317" # exporterの利用するプロトコル: gRPC

volumes:
  pgdata:
  mongo-data:
  mongo-config:
  influxdb2-data:
  influxdb2-config:
