// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForInsertURLs implements pgx.CopyFromSource.
type iteratorForInsertURLs struct {
	rows                 []InsertURLsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertURLs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertURLs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UrlAddress,
		r.rows[0].CategoryCode,
	}, nil
}

func (r iteratorForInsertURLs) Err() error {
	return nil
}

// @desc: Deprecated. insert urls if not existed
func (q *Queries) InsertURLs(ctx context.Context, arg []InsertURLsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"urls"}, []string{"url_address", "category_code"}, &iteratorForInsertURLs{rows: arg})
}
