// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	CategoryID   int32
	CategoryCode string
	JpName       string
	IsDeleted    pgtype.Bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Url struct {
	UrlID           int32
	UrlAddress      string
	CategoryCode    string
	BookmarkCount   pgtype.Int4
	NamedUserCount  pgtype.Int4
	PrivateUserRate pgtype.Float8
	IsDeleted       pgtype.Bool
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type User struct {
	UserID        int32
	UserName      string
	BookmarkCount pgtype.Int4
	IsDeleted     pgtype.Bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Userurl struct {
	UserUrlID int32
	UserID    int32
	UrlID     int32
	IsDeleted pgtype.Bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
