// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	UrlID      int32
	UrlAddress string
	IsDeleted  pgtype.Bool
}

type User struct {
	UserID    int32
	UserName  string
	IsDeleted pgtype.Bool
}

type Userurl struct {
	UserUrlID int32
	UserID    int32
	UrlID     int32
	IsDeleted pgtype.Bool
}
